server:
  port: 8076

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://RegisterLoginService    # service name from Eureka
          predicates:
            - Path=/login-register/**       # single predicate covers all paths
          filters:
            - StripPrefix=0                 # keep /login-register/... as-is

        - id: income-service
          uri: lb://IncomeService           # service name from Eureka
          predicates:
            - Path=/income/**               # Gateway route
          filters:
            - StripPrefix=0

        - id: expense-service
          uri: lb://ExpenseService          # service name from Eureka
          predicates:
            - Path=/expense/**              # Gateway route
          filters:
            - StripPrefix=0
